### ISSUE TITLE
Java NullPointerException when trying to deserialize OTS file

### ISSUE THREAD

**Issue by simbro** [opentimestamps/java-opentimestamps#26]
When I try to verify a timestamp using the Java library, I am running into a Java NullPointerException.

This is my code:

```
byte[] originalFile = Files.readAllBytes(fileData.get("absoluteFilePath"));		
byte[] originalBytes = new String(originalFile).getBytes("UTF-8");
String originalHex = DatatypeConverter.printHexBinary(originalBytes);
	    
 byte[] otsFile = Files.readAllBytes(fileData.get("otsFilePath"));
byte[] otsBytes = new String(otsFile).getBytes("UTF-8");
String otsHex = DatatypeConverter.printHexBinary(otsBytes);

// below is from the examples...

DetachedTimestampFile detached = DetachedTimestampFile.from( new OpSHA256(), originalFile );
DetachedTimestampFile detachedOts = DetachedTimestampFile.deserialize(ots);

HashMap<Chains, VerifyResult> result = OpenTimestamps.verify(detachedOts,detached);
```

And this the exception:

```
java.lang.NullPointerException: null
	at com.eternitywall.ots.Timestamp.doTagOrAttestation(Timestamp.java:101) ~[java-opentimestamps-1.16.jar:na]
	at com.eternitywall.ots.Timestamp.deserialize(Timestamp.java:89) ~[java-opentimestamps-1.16.jar:na]
	at com.eternitywall.ots.DetachedTimestampFile.deserialize(DetachedTimestampFile.java:107) ~[java-opentimestamps-1.16.jar:na]
	at com.eternitywall.ots.DetachedTimestampFile.deserialize(DetachedTimestampFile.java:120) ~[java-opentimestamps-1.16.jar:na]
	at com.fmr.ots.FileTimestampController.verifyDocument(FileTimestampController.java:110) ~[classes/:na]
```

Are there examples for how to read in the OTS and original file, or a complete example of how to use the Java client in code?

**Comment by lvaccaro** [comment]
Hi, which version are you using? can you attach your ots file?

**Comment by lvaccaro** [comment]
Hi @simbro , the ots file contains only the header (with sha256 of the original file), but no Merkle path; also the info command fails because the ots is invalid. There was a mistake during stamp procedure, as no internet connection to calendar server or wrong saving method.

**Comment by simbro** [comment]
Thanks Luca, much appreciated!

Yes I did indeed have an error with the stamping function, I've resolved that now and it appears to be functioning, though I'm till not able to upgrade or verify.


These are the complete logs of stamping, and then upgrading a file:

```
Submitting to remote calendar https://alice.btc.calendar.opentimestamps.org
Submitting to remote calendar https://bob.btc.calendar.opentimestamps.org
Submitting to remote calendar https://finney.calendar.eternitywall.com
2018-11-18 23:09:13.567  INFO 13800 --- [nio-8080-exec-4] com.example.ots.FileTimestampController      : File sha256 hash: 064b96390bff5e3764b0957cbbe1fdaa4ac596b47ffab0161a664e12c01759de
Timestamp:
append b68f4e4251c8af843f2b76f68819d529
sha256
 -> append 66127344d79b5e419fa95054d90182f7
    sha256
    prepend 5bf1f118
    append 09247e79a62e3fb5
    verify PendingAttestation('https://alice.btc.calendar.opentimestamps.org')
 -> append 9953f201e8f4298638da588c4ea691ab
    sha256
    prepend 5bf1f119
    append 811d0108897869f8
    verify PendingAttestation('https://bob.btc.calendar.opentimestamps.org')
 -> append e1d19dfff7eacb3d74dc2080674ef0fe
    sha256
    append caf30d75013f13d86e8932e082295fe2
    sha256
    prepend 5bf1f119
    append 4cd34e8a6b1c0f43
    verify PendingAttestation('https://finney.calendar.eternitywall.com')

https://bob.btc.calendar.opentimestamps.org/timestamp/5bf1f1192a65812e1bbf8c9056266182a8f2fa3e855ae5f121699da2f91810e59c7b7d76811d0108897869f8 exception java.io.FileNotFoundException: https://bob.btc.calendar.opentimestamps.org/timestamp/5bf1f1192a65812e1bbf8c9056266182a8f2fa3e855ae5f121699da2f91810e59c7b7d76811d0108897869f8
Calendar https://bob.btc.calendar.opentimestamps.org: null
null
https://finney.calendar.eternitywall.com/timestamp/5bf1f119013a731c524b830dcc6da069a34c288782adebebfbedd66930df3d3712c6f2354cd34e8a6b1c0f43 exception java.io.FileNotFoundException: https://finney.calendar.eternitywall.com/timestamp/5bf1f119013a731c524b830dcc6da069a34c288782adebebfbedd66930df3d3712c6f2354cd34e8a6b1c0f43
Calendar https://finney.calendar.eternitywall.com: null
null
https://alice.btc.calendar.opentimestamps.org/timestamp/5bf1f11885a0d1d2ccb58753b9466d28d564e3bd3d489685c55250840a93a7199a58a20709247e79a62e3fb5 exception java.io.FileNotFoundException: https://alice.btc.calendar.opentimestamps.org/timestamp/5bf1f11885a0d1d2ccb58753b9466d28d564e3bd3d489685c55250840a93a7199a58a20709247e79a62e3fb5
Calendar https://alice.btc.calendar.opentimestamps.org: null
null
Timestamp not upgraded
```

These are the three controller methods that handle timestamping, upgrading and verifying - I'm not sure where I'm going wrong:

```
@RequestMapping("/timestamp/{fileId}")
public String timestampDocument(@PathVariable("fileId") Long fileId) throws Exception {
	HashMap<String, Path> fileData = getFileDataFromId(fileId);
	
	byte[] data = Files.readAllBytes(fileData.get("absoluteFilePath"));
	
	try {
		DetachedTimestampFile detached = DetachedTimestampFile.from( new OpSHA256(), data );
		
		String infoResult = OpenTimestamps.info(detached);
		
		logger.info(infoResult);
		
		Files.write(fileData.get("otsFilePath"), detached.serialize());
		
		return infoResult;
	} catch (Exception e) {
		e.printStackTrace();
		
		throw e;
	}
}

@RequestMapping("/verify/{fileId}")
public HashMap<Chains, VerifyResult> verifyDocument(@PathVariable("fileId") Long fileId) throws Exception {
	HashMap<String, Path> fileData = getFileDataFromId(fileId);
	
	byte[] data = Files.readAllBytes(fileData.get("absoluteFilePath"));
	byte[] otsFileContent = Files.readAllBytes(fileData.get("otsFilePath"));

	DetachedTimestampFile detached = DetachedTimestampFile.from( new OpSHA256(), data );
	DetachedTimestampFile detachedOts = DetachedTimestampFile.deserialize(otsFileContent);

	HashMap<Chains, VerifyResult> result = OpenTimestamps.verify(detachedOts, detached);
	
	if (result == null || result.isEmpty()) {
		System.out.println("Pending or Bad attestation");
	} else {
		result.forEach((k, v) -> System.out.println("Success! " + k + " attests data existed as of "+ v));
	}
	
	return result;
}

@RequestMapping("/upgrade/{fileId}")
public String upgradeDocument(@PathVariable("fileId") Long fileId) throws Exception {
	HashMap<String, Path> fileData = getFileDataFromId(fileId);
	
	byte[] otsFileContent = Files.readAllBytes(fileData.get("otsFilePath"));

	DetachedTimestampFile detachedOts = DetachedTimestampFile.deserialize(otsFileContent);
	
	boolean changed = OpenTimestamps.upgrade(detachedOts);
	
	if(!changed) {
	   System.out.println("Timestamp not upgraded");
	   
	   return "Timestamp not upgraded";
	} else {
	   System.out.println("Timestamp upgraded");
	   
	   return "Timestamp upgraded";
	}
}
```

**Comment by lvaccaro** [comment]
Now you are able to stamp and check PendingAttestation in receipt; upgrade and verify look good, but you need to wait before upgrading.

Remember: It takes a few hours for the timestamp to get confirmed by the Bitcoin blockchain; we're not doing one transaction per timestamp.

**Comment by simbro** [comment]
So I was able to upgrade successfully, and the logs show the "Timestamp upgraded" message from above.

However, even after 10 hours, I'm still seeing the "Pending or Bad attestation" in the logs.  When I use the online verifier on opentimestamps.org, I get the following message:

> "Bitcoin block 550636 attests existence as of 2018-11-18 GMT"


[See timestamp info here](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108064b96390bff5e3764b0957cbbe1fdaa4ac596b47ffab0161a664e12c01759def010b68f4e4251c8af843f2b76f68819d52908fff01066127344d79b5e419fa95054d90182f708f1045bf1f118f00809247e79a62e3fb5ff0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f726708f020e4998357657455ede5210041009cb82b150c6abe74de43c39cc8b7714122265708f020598b716c380b9098bd6e7ab4632167cd65e775a3c3624721fefb74ce0c9baeba08f120a8a7af0fc0b3d2cc1a5e1fcff8e57aed7f14f55e691121f05a3c122697a023b308f0208ea342e88d542341885bab1a1c309d552964d43684662a265b3830194617e3e408f0204bf7207979b7c8f9b5d45f033f1838671e4614003e8925aeabc900e1d65bcd5308f120412da8eb2947567e43c571af98c6954448b8144ed92757cc7f474b6c8145292908f120dd0fa5e886125191f25cdafd9c9a0d7ed72191c2f3eeb01a5acee63e3aab502608f020113ead1df02114066b9f85cf8fd7ce469e30ad39ff0dd87159a7bfd5f75fce6a08f1710100000001a786c439c7781a853f33ae5067ef2e9678b0014bcc9c94e9b89dd6e7c0a9b67b0000000017160014d6578106065c9e520fcea05a245ace757e2d27bbfdffffff02ce6b37000000000017a9142882f37c6d8abab4f5b50d7a7614bf3dbdec77e7870000000000000000226a20f004eb6608000808f02034a5dfcb1446622021da1d01726eb09473a43696cd32586386aeb56dea1558050808f12033fa498c734797820e12c3eb6c15a3faed01a25c90b508c5c4e72a8a141ee6790808f020119dcb056fb5bfd3ddb00932e28dcd00980daaef842c0fbb26cf30f7877543fb0808f120a2dac9ea3b79ec71ab5ad9a0a8ed5093df3f4a39d52693d255130b65eb1efffa0808f0206c8675b7bca31591df2dee25e4cfcb923e505e135d8f8113ee418967fadd160d0808f020ee1dc6a38f6058856d496c29aaaabf1507d833a0e9007cc8e0e9fefc786802bb0808f120cc3491594c568255e28c945c8c44e671347bade3c94f5a62c3b2877609d12cba0808f020166a5be2c31e7deb99fac83a84eb6c3cb30d6675066e8fee94c285142d9d66780808f0203702c16f3e0502e1f3e73715fb2b4be2ad07f109faf35af043e816b9a68809620808f1206a4a97a7ea22f91203b8568756bb564db0c48827f59edff655732b73fa0b9cbc0808000588960d73d7190103eccd21fff0109953f201e8f4298638da588c4ea691ab08f1045bf1f119f008811d0108897869f8ff0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f726708f1209ea2287d9a5116a39988a07e01ac1f843d25d40e24d69cdff815133dd76781a508f0207a40ce7b89df6f7b6e161f023a9bef9c13528a097060505c51c8526948b4c72b08f02003b4d3f62e74e909e9c7664253c1dc54361d159da4810abebd63cfc204aed7a708f1200d1866285340a5ded93df32446d3c600b1adb2a571c74acf4e474566d8e4303a08f020be271d96413c294042a29311c7d19b9a945a2eb30302edf25716dc4db82732d308f1208e981248ae4e2f3d55ff5c4598f2d24cba5cb6c01e93a2fd032aa9515435a46c08f1710100000001007c55459a9c8f9ea48bfb4f1bd29b249282187ab7522654116402d458b613d60000000017160014a200573f0773c4929c3add5eab49cc9413a6b5a3fdffffff02138072000000000017a91471a4ba07d75eafb4ed365b32b7feab54ce605173870000000000000000226a20f004eb6608000808f0202ec143b1e6635c18be683fbfaf322c96d2d52ac9a5b62e0ab8ae27c5a057cd3d0808f1209d706e181935ffa020c75362d750737c0f984de66d47240e085a9f9f468dd3430808f12098e7c649b9b3ae85cd66bd0cb8b4f86a767f8ec8b8b4a98467209a82e4e494ad0808f120a2dac9ea3b79ec71ab5ad9a0a8ed5093df3f4a39d52693d255130b65eb1efffa0808f0206c8675b7bca31591df2dee25e4cfcb923e505e135d8f8113ee418967fadd160d0808f020ee1dc6a38f6058856d496c29aaaabf1507d833a0e9007cc8e0e9fefc786802bb0808f120cc3491594c568255e28c945c8c44e671347bade3c94f5a62c3b2877609d12cba0808f020166a5be2c31e7deb99fac83a84eb6c3cb30d6675066e8fee94c285142d9d66780808f0203702c16f3e0502e1f3e73715fb2b4be2ad07f109faf35af043e816b9a68809620808f1206a4a97a7ea22f91203b8568756bb564db0c48827f59edff655732b73fa0b9cbc0808000588960d73d7190103eccd21f010e1d19dfff7eacb3d74dc2080674ef0fe08f010caf30d75013f13d86e8932e082295fe208f1045bf1f119f0084cd34e8a6b1c0f43ff0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d08f0203b9a8a99e1b8480903dbf906c5c22a3b245903a146c35069bf0885946d133c5508f1207b576409bf71ab169390c928ad3abeb933d12bc9befede6de900f8cb8a03ce6708f120d626f3736d4b421bd12978c54ab0f28e3515c01fc54ea91dac61bb664fb9fd6808f120b299c7bbc2033eb173c98b0a1ba5a5033056cd0b681e000e4e391555bc9fc87108f1201880458842acd6c8f228e77069d85f5239ce304fb338318e0894ea1867bc630008f120828b28a11cc2f57442faf09d3c57a1459442a6c6270bb301f004f64fb96ec43708f120d3fff50ef4bacf66587f44fb03dbd52d3806a800a875ea3ed12739c2bc50320f08f020461da0372630567561495fddd858e72e416dd6df7f3546f3802bcd6bd932377408f020413e2d5fecca5b07a10c47e116012bf8d92fb10e37764516cf432e33945d09ae08f171010000000125cf144c36399ec7ee6340f5b4754080523e4f28ad42922ba81a90b56642140b0000000017160014f2148fa9d30fbf38f510d0aa8f29ff7b6a7fa610fdffffff02204b0c000000000017a91458be8061b4000628ed4c5937dce1d6d08d419a67870000000000000000226a20f004eb6608000808f1202fe7f35dd5d1c2e7727d7a4f49495af7582ea13d1ee66157e8da22f76aaaa4e60808f12033fa498c734797820e12c3eb6c15a3faed01a25c90b508c5c4e72a8a141ee6790808f020119dcb056fb5bfd3ddb00932e28dcd00980daaef842c0fbb26cf30f7877543fb0808f120a2dac9ea3b79ec71ab5ad9a0a8ed5093df3f4a39d52693d255130b65eb1efffa0808f0206c8675b7bca31591df2dee25e4cfcb923e505e135d8f8113ee418967fadd160d0808f020ee1dc6a38f6058856d496c29aaaabf1507d833a0e9007cc8e0e9fefc786802bb0808f120cc3491594c568255e28c945c8c44e671347bade3c94f5a62c3b2877609d12cba0808f020166a5be2c31e7deb99fac83a84eb6c3cb30d6675066e8fee94c285142d9d66780808f0203702c16f3e0502e1f3e73715fb2b4be2ad07f109faf35af043e816b9a68809620808f1206a4a97a7ea22f91203b8568756bb564db0c48827f59edff655732b73fa0b9cbc0808000588960d73d7190103eccd21)
