### ISSUE TITLE
ConcurrentModificationException on  Timestamp shrink() method

### ISSUE THREAD

**Issue by tweilbach** [opentimestamps/java-opentimestamps#7]
I received a bunch of shrink error messages when I tried calling upgrade in a loop for a bunch of files. Individual upgrade calls for any of the files worked but as soon as I performed an upgrade in a loop the error occurred. The error is from the shrink() method:

`INFO: Shrink error: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at com.eternitywall.ots.Timestamp.shrink(Timestamp.java:226)
	at com.eternitywall.ots.Timestamp.shrink(Timestamp.java:231)
	at com.eternitywall.ots.Timestamp.shrink(Timestamp.java:231)`

I'm no Java boffin but a quick google told me it is due to the fact that the collection is being modified while being iterated over. Line 233 `this.ops.remove(op);` modifies the collection and causes an error on `next()` call on line 226.

I fixed the issue by converting the loop to an Iterator as per smart people on the internet.

**Comment by tweilbach** [comment]
My first ever Pull request will be forthcoming :)

**Comment by RCasatta** [comment]
closing because already addressed
